### ISSUE TITLE
Spec verified profile fields

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#141]

**Comment by michaelsena** [comment]
* which verifications
* how we're going to implement them

**Comment by michaelsena** [comment]
# Feature Description

We should add more profile fields to the [3box.io](http://3box.io) dapp so that users can add veracity and authenticity to their Ethereum profile. By allowing users to verify certain attributes of their identity, from web2 social verifications to verified email and mobile contact info, we can bootstrap trust onto the 3Box network and make partners lives easier because they will be able to have greater confidence in the information provided by users.

**Developer Need**

As a dapp developer I need to get pre-verified contact information about my users, so I don't need to verify their email when I onboard them.

As a dapp developer I need to link my user's Ethereum accounts with their existing forms of identity so users that already know each other on other platforms can have greater trust in each other on my platform.

**User Need**

As a [3box.io](http://3box.io) dapp user, I would like to link my existing accounts because my information and friends live there already.

---

There are a few major categories of user profile info in the 3box dapp.

- Basic  *subjective*
- About  *subjective*
- **Contact**  *verified*
- **Linked (Social) Accounts**  *verified*
- Experience  *subjective*

---

# Contact

Allows users to verify contact information.

**New Fields**

`email`: only accept valid email formats (i.e. xxxxxxx@yyyyy.zz) of a max length.

`mobile`: only accept valid phone number formats.

# Linked (Social) Accounts

Allows users to to connect with existing sources of social identity and reputation.

**New Fields**

`twitter`: string with max length

`github`: a valid URL with max length

---

# Implementation

For implementing `twitter`, `mobile` `email`, we can possibly use Origin Bridge. https://github.com/OriginProtocol/origin/tree/master/origin-bridge

## Origin Bridge

Origin Bridge is a REST API that allows javascript applications to interact with Origin's backend Identity Verification Service. Origin provides claims to web3 identities that bridge the gap between various web2 social identity networks.

---

# Future Ideas

`facebook`

`linkedin`

`discord`

`telegram`

`airbnb`

---

# Design Spec [DRAFT]

![new edit profile fields concept](https://user-images.githubusercontent.com/5216274/48928677-69695b80-eeaf-11e8-96c2-c822d42ea39a.png)

**Comment by michaelsena** [comment]
@oed over to you now for finalizing the implementation deets.

**Comment by oed** [comment]
Looking at the origin bridge. Looks cool but a bit limited. Seems like you can only verify erc725 identities. The claims that you get back seems to lack the concept of an issuer, which is quite problematic if you are interested in verifying their authenticity. Would probably be a good idea to sync with them to see where their head is at.

**Comment by michaelsena** [comment]
Thanks @oed, and that's interesting. Are there any other open source account verification implementations that you know of which could be useful for these cases?

**Comment by oed** [comment]
I'm not aware of any implementations that provides us with what we need unfortunately :/ I'm also a bit worried that this endeavor might grow in scope quite quickly, so I propose that for simplicity we hold of on verifying mobile and email for now. This will allow us to do this in a more iterative way. It also removes the need for additional infrastructure for now. Below is a rough draft for the hole thing, but I think we can start with just the github and twitter verifications to not overwhelm ourselves. 

---
We need two different modules. `3box-verifications` and `did-account-verification-service`.
The first one can verify and generate client side account proofs as well as verify claims issued by third party services (e.g. the `did-account-verification-service`). It will also act as a helper to generate these verification. 


## 3box-verifications
This is a js library that has the following methods.
#### .verifyGithub(box, gistUrl)
`box` - a 3box instace for the user
`gistUrl` - a url to a gist that contains the users DID

This method checks if the gist contains the DID corresponding to the user. If so it adds the users github name to `github`, and the gistUrl to `githubProof`, both in the public profile of the user. Otherwise it throws an error.

#### .hasVerifiedGithub(box)
`box` - a 3box instace for the user

This function validates that the gistUrl in `githubProof`of the public profile is a valid proof for the username in `github` of the public profile. It returns true if so.

#### .verifyTwitter(box, tweetUrl)
`box` - a 3box instace for the user
`tweetUrl` - a url to a tweet that contains the users DID

This method checks if the tweet contains the DID corresponding to the user. If so it adds the users twitter name to `twitter`, and the tweetUrl to `twitterProof`, both in the public profile of the user. Otherwise it throws an error.

#### .hasVerifiedTwitter(box)
`box` - a 3box instace for the user

This function validates that the tweetUrl in `tweetProof`of the public profile is a valid proof for the username in `twitter` of the public profile. It returns true if so.

#### .requestEmailVerification(emailAddress, callbackUrl)
Sends a request to the `did-account-verification-serivce` with the given params.

#### .verifyEmail(box, verificationCode)
`box` - a 3box instace for the user

Sends a request to `/verify-email-code` of the `did-account-verification-serivce` with the given params. If successful it stores the email in the private store in the  `email` key, along with the attestation from the verification-service in the `emailProof` key of the private store.

#### .hasVerifiedEmail(box)
`box` - a 3box instace for the user

This function validates that the attestation in `emailProof`of the private profile is a valid attestation for the email in `email` key of the private profile. It returns the issuer DID if the attestation if so.

## did-account-verification-service
This is a service that verifies accounts that needs a third party to verify. When an account has been verified it issues an attestation to the given user. The service has a [https-did](https://github.com/uport-project/https-did-resolver), and uses [did-jwt](https://github.com/uport-project/did-jwt) to create the claims.
Has the following REST apis:

### `/request-email-verification`
`POST`
```js
{
  email: <user@service.com>,
  did: <did:method:id>,
  callbackUrl: <the url that the verification email will link to>
}
```
Response:
```js
{
  status: 'success'
}
```  

Generate a random number `N` that is stored along with a timestamp and the email address. Then sends an email to the given email that contains a link that the user can click `callbackUrl + '?code=<N>'`

### `/verify-email-code`
`POST`
```js
{
  email: <user@service.com>,
  code: <the code sent to the callback url>
}
```
Response:
```js
{
  status: 'success',
  data: {
    attestation: <a did-jwt from the verification service claiming that the email is correct>
  }
}
```
