### ISSUE TITLE
Enable getProfile for addresses in the activity feed

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#246]
@michaelsena commented on [Tue Dec 04 2018](https://github.com/3box/3box-activity/issues/14)

---

@oed commented on [Wed Dec 05 2018](https://github.com/3box/3box-activity/issues/14#issuecomment-444431024)

What does this have to do with 3box-activity? Should happen in the dapp imo.

---

@oed commented on [Wed Dec 05 2018](https://github.com/3box/3box-activity/issues/14#issuecomment-444431283)

If in the dapp it could load and display ethereum addresses first, then show image and name once they are loaded.

**Comment by dazuck** [comment]
One thing this made me think while figuring out how to do efficiently - it might be nice to not just have this work in the background but for it to actually demonstrate the functionality to people. E.g., instead of just replacing the address with a profile throughout, perhaps there's a "getprofile' button next to each address that has a 3box and the user clicks the button to replace it. This bakes education & appreciation into the product where it may be missed otherwise. 

Only if this is as easy/efficient for an MVP. Just looking for ways to 'get points' for new fn.

**Comment by oznekenzo** [comment]
@dazuck I think making the 3box layer evident to users is a great idea - instead of making users explicitly push a button to getProfile though, maybe we highlight that grouping of data with a subtle 3Box water mark, or perhaps do something similar with eth addresses with no metadata but provide a button on hover for users to send that Eth address an invitation to add color / richness / metadata to their ethereum address via 3Box

**Comment by michaelsena** [comment]
@oznekenzo we have no mechanism to message users right now so the last option wouldn't work. I'm not opposed to indicating which ones are 3Box profiles with a very subtle mark, but this is low priority and can be added later. 

I don't like the idea of a button however, since that's bad UX and not "magic" and adds too much overhead.

Will consider in the design, which I'm about to start now, but you won't tackle feed until 2H of this sprint so I have some time :)

**Comment by tzapu** [comment]
hey guys, fwiw, what we did in our app to highlight to people that data is provided by 3box in an obvious way (we think) is to link back to you next to the data.
![screenshot 2019-01-16 12 03 51](https://user-images.githubusercontent.com/2983312/51241711-0237c700-1987-11e9-8adf-6c7b6f80422e.png)

**Comment by michaelsena** [comment]
Thanks @tzapu I think that looks great. Thanks for the link back to our site! 💟

**Comment by michaelsena** [comment]
@oznekenzo we're planning to use the graphql API for this right?

**Comment by oznekenzo** [comment]
We should

**Comment by oznekenzo** [comment]
It's going to take some time however to set up graphql in the dapp

**Comment by michaelsena** [comment]
Can you describe the tradeoffs in more detail, and the time required to implement graphql. What is "some time" - that's not enough information for me. TY!

**Comment by zachferland** [comment]
using graphql through the lib function shouldn't be any more difficult than using get profile, query language super simple and response just slightly different to parse.  Eventually it could be more work (and some benefit) to use the graphql end point directly with one of the react graphql clients. Let me know if you need more details on any parts

**Comment by oznekenzo** [comment]
@zachferland thanks - I just recently set up graphql on a hobby project last week but couldn't remember which part of it exactly was just client side and which was server side. I'll look into it shortly and if I have any more questions, I'll let you know!
@michaelsena Sorry - I didn't provide more info because I need to look into it more to provide a better answer.  But according to Zach it shouldn't take too long, looks like.

**Comment by oznekenzo** [comment]
@michaelsena the only tradeoff is the slightly slower implementation, as I've never consumed from a graphql api before.  But since you're only getting back the exact data that you need, should pay off in the form of quicker get requests with smaller payloads.
