### ISSUE TITLE
Allow users to create notes directly in their drive 

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#406]
This would add a button to Drive, which would open a modal and would allow a user to choose a type (image, note, etc), the space to store it in, and the privacy (public, encrypted). Ideally the user could also create a new space from this modal if they want to store a piece of data in a space that doesn't yet exist.

Unlock wants to use this to allow users to add purchased keys to their public Unlock space.

** Requested by the Unlock team and others, such as Harrison and Ryan from Foam

**Comment by kuhnchris** [comment]
Do you mean "Data" or "Drive"? 
For "Data" we'd first need to add a possibility to create new spaces IMHO, and then to add new files.

Entry point AFAIK:
https://github.com/3box/3box-dapp/tree/master/src/views/Spaces

Want me to try?

**Comment by michaelsena** [comment]
@oed how should we store the content uploaded by the users here? Perhaps something like this?

If a new note is created:
`note.yourNoteName`: `'Note content.'`

If an image file (png, gif, pdf, jpg) is uploaded:
`image.yourFileName`: IPFS ImageObject schema

**Comment by oed** [comment]
Is the intent that data is uploaded to INFURA, Pinata, or similar service here? If it's a paid service how will that be handled? 

I don't see a problem with using keys like that for now @michaelsena. I would probably prefer if notes are stored in IPFS as well since we don't necessarily know the length of any text document. 

In the longer term we need a better strategy for creating a more file system like structure for things like this.

**Comment by michaelsena** [comment]
@kuhnchris for this current implementation, we decided that it would be best to just allow users to create text notes from drive, and put off the file uploading
